### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by WilsontheWolf** [jikamens/allow-locked-remote-desktop#1]
Hello There,

Thank you very much for making this. I recently updated to Gnome 42 and would like to have this package be updated. I'm not sure if theres any code needing to be changed, or if its just a metadata update. Thank you very much

**Comment by numeratorjik** [comment]
I would also like it to support GNOME 42, but unfortunately I can't test it on GNOME 42 because I use Ubuntu and remote desktop support is currently broken in Ubuntu Jammy (https://bugs.launchpad.net/ubuntu/+source/gnome-remote-desktop/+bug/1964976). Can you test the attached and tell me if it works for you? To install this, uninstall the extension if you already have it installed, then log out and log back in just to be sure, then run `gnome-extensions install filename.zip` from a terminal window, where `filename.zip` is the path where you saved the attached file, then log out and log back in again just to be sure, and see if you are able to remote desktop in when the screen is locked after that.

[allowlockedremotedesktop@kamens.us.shell-extension.zip](https://github.com/jikamens/allow-locked-remote-desktop/files/8454515/allowlockedremotedesktop%40kamens.us.shell-extension.zip)

**Comment by jikamens** [comment]
Woops, just realized I posted the above from my work Github account. Yes, it really is I, the maintainer of the add-on, who posted the above comment. Just in case you were nervous about installing a ZIP provided by someone other than the maintainer. ;-)

**Comment by WilsontheWolf** [comment]
This seems to work just fine. Thanks!

**Comment by jikamens** [comment]
Thanks, pushed new release to extensions.gnome.org.
