### ISSUE TITLE
Not working on Fedora 36

### ISSUE THREAD

**Issue by LulinS** [jikamens/allow-locked-remote-desktop#2]

**Comment by jikamens** [comment]
This probably has something to do with the switch from VNC to RDP as the remote desktop protocol.

Unfortunately, I can't troubleshoot further because with all currently available Fedora 36 updates installed in the VM I set up to debug this, gnome-remote-desktop in the VM crashes every time I attempt to connect to the VM with xfreerdp. :shrug: 

I will circle back and take a closer look at this if/when I can actually get remote desktop to work with Fedora 36 as the target system _without_ the screen locked, at which point I may be able to figure out how to get it to work _with_ the screen locked.

**Comment by jikamens** [comment]
I managed to get RDP-based gnome-remote-desktop working on Ubuntu Jammy and tested this extension there, and it's working just fine. As noted above, I can't troubleshoot this further on Fedora 36 until gnome-remote-desktop stops crashing there when I try to connect to it, so I will check in periodically to see if that has been fixed and, when it has, investigate further.

**Comment by jikamens** [comment]
I just tried again. The gnome-remote-desktop service is still segfaulting on Fedora 36 when I connect to it using xfreerdp from another box, so I still can't troubleshoot this further. Will continue to check it on it occasionally to see if they've fixed the crash yet.

**Comment by jikamens** [comment]
Tried again today. Gnome-remote-desktop on Fedora is still segfaulting when I connect to it, so I still can't troubleshoot this further.

**Comment by jikamens** [comment]
Just tried again. Gnome-remote-desktop on Fedora 36 is still crashing when I connect to it, so I still can't troubleshoot this further.
At this point I'm going to start checking monthly instead of weekly.

**Comment by starfreck** [comment]
Any updates on this? Currently, I switched to xrdp as an alternative.

UPDATE: I hate to say this but I switched to [ThinLinc](https://www.cendio.com/thinlinc/download) until GNOME starts supporting headless remote sessions on Wayland or this extension gets fixed. ThinLincis much better and faster than xrdp.  It supports PipeWire on X11 so you will have the same features as gnome-remote-desktop. It has Native Clients as well as the HTML5 client. The only downside is it is not an Open Source product. But you can use it for free for up to 10 users.

**Comment by jikamens** [comment]
gnome-remote-desktop in my VM is still crashing every time I connect over RDP to the VM, so I still can't debug this further on Fedora.

**Comment by jikamens** [comment]
Still crashing, so still can't debug this further.
Perhaps Fedora 37 will be better. :-/

**Comment by jikamens** [comment]
I was never able to debug this issue in Fedora 36 because every time I attempted to connect to my Fedora 36 machine over RDP the RDP server crashed as described above.

I just upgraded my machine to Fedora 37 today and RDP is working fine, so great! However, Allow Locked Remote Desktop is _also_ working fine, i.e., I can't reproduce the issue. With the extension installed and activated, if I am connected to the machine via RDP and I lock the screen I stay connected, and if I attempt to connect to the machine while it is locked I am able to connect. With the extension not installed or deactivated, neither of those things is the case. Everything appears to be working properly. Since I can't reproduce, I can't do anything about this issue. :shrug: Feel free to reopen if you figure out what's different about your situation which is causing problems for you.
