### ISSUE TITLE
Pop! OS 22.04

### ISSUE THREAD

**Issue by hkdb** [jikamens/allow-locked-remote-desktop#4]
Hi there! Thanks for making this much needed extension!

I have been experiencing an issue that I am not sure if it's related to this extension or if it's something to do with Pop! OS itself so if nothing else, I am just looking for your thoughts on this. Here goes:

Once in a while when the screen is locked and blanked for more than 5-10 seconds, I seem to loose keyboard input when the screen is waken with a mouse click or keyboard stroke. This is however especially 100% reproduceable if I try to connect via RDP and wake the screen. I have RDP enabled with the "Allow Locked Remote Desktop" extension installed and it works well except for when the screen is locked/blanked for a while. Then keyboard input is completely unresponsive. The only way out of it is if I locally do ctrl-alt-f1 (so I guess I don't loose all keyboard input after all) and login. Then it will bring me back to my desktop unlocked and intact.

I am able to reproduce this on my Intel based Laptop and an AMD based mini pc both running Pop! OS 22.04.

This also happens 100% of the time if I try to use VNC, Rustdesk or even Barrier so it might be related to virtual input of sorts?

When I tailed my syslog while reproducing the issue, I also see this:
```
gnome-shell[5092]: Remote desktop connections while screen is locked are now DISABLED
```
Is that message supposed to show if the extension is working properly?

FWIW, and it's a long shot since rolling distros have much diff versions of everything, I have a fully updated Garuda Linux (Gnome) machine that does not have the same behavior with your extension installed.

Any thoughts? Thanks much!

**Comment by jikamens** [comment]
Two things:

1. The keyboard issue you are seeing has nothing to do with this extension. I don't know what's causing those issues, but it's not this. I wonder if perhaps your computer is going to sleep and not reconnecting the keyboard immediately when it is woken up, but that's just a guess. :shrug:
2. I looked into the DISABLED message you're seeing and it turns out that's a confusing artifact of how gnome-shell manages extensions when the screen is locked. After some digging I can't find any way to work around that, so I just pushed a change to disable the log message. If you want all the nitty-gritty details, see 0aec6cdf6c27204b7b9cfe8b88d4d00f4afa86f5.

**Comment by jikamens** [comment]
Update on this: The GNOME Shell maintainers helped me understand how to do the logging accurately, so those log messages when remote desktop connections while locked are enable/disabled have been restored in the current version of the extension on extensions.gnome.org.

**Comment by hkdb** [comment]
Thanks for the quick response! Really appreciate it!

**Comment by hkdb** [comment]
@jikamens btw, FYI, I noticed some new updates today and within those updates included gnome-shell and remote-desktop. After the update, this issue was completely resolved. Rustdesk also started working as well. So I think it must have been a known bug fix in gnome-shell that was included in the latest update. Thanks again!
